Traceback (most recent call last):
  File "D:\GithubProject\mcv-c6-2024-team3\Week1\optimization_task2_1.py", line 54, in train
    modelo.fast_test(alpha=config.alpha, ro = config.rho)
  File "D:\GithubProject\mcv-c6-2024-team3\Week1\task2_1.py", line 177, in fast_test
    shutil.rmtree(outputFolder)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 633, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 631, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] El directorio no está vacío: 'framesResult_adaptive'